Mon Mar 28 14:24:30 CST 2022
Empieza validaci√≥n de actualizaciones diarias

Cambiando nombre de archivos...
Descargando archivo nuevo...
Leyendo archivos...
Comparando archivos...
2022-03-17 02:23:18.251+00
Traceback (most recent call last):
  File "compare.py", line 118, in <module>
    main()
  File "compare.py", line 116, in main
    compareFiles(actual,anterior,paths.path_history,paths.path_changelog)
  File "compare.py", line 34, in compareFiles
    date = functions.getDate(actual.updatedAt[i])
  File "/home/vbass/daily_update/catalogo-agrobiodiversidad/functions.py", line 22, in getDate
    date = datetime.strptime(date[0], "%Y-%m-%d %H:%M:%S" )
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2022-03-17' does not match format '%Y-%m-%d %H:%M:%S'
git add history.md changelog.md
git commit
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
	modified:   scripts/logfile.txt

Untracked files:
	__pycache__/
	actualizaciones_agro.sh
	agro_actual.csv
	agro_anterior.csv
	agro_prueba.csv
	compare.py
	compareZacatuche.sh
	contraZacatuche.csv
	estatus.py
	functions.py
	logfile.txt
	paths.py
	pruebas.sh

no changes added to commit
git push
Everything up-to-date
Proceso terminado!
